name: Fabio's Welt
description: Erfahrungsberichte, Ideen und Alltagssituationen. Alles, was nicht in 140 Zeichen Platz hat.

url: http://fabios.world
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: true
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Über mich
   url: /about
 - title: Kontakt
   url: /contact

gems:
 - jekyll-paginate
